version: '3.9'
services:
  db:
    image: mariadb:10.5.8-focal
    volumes:
      - ./db/_data:/docker-entrypoint-initdb.d
      - ./db/db:/var/lib/mysql
    ports:
      - 3316:3306
    environment:
      MYSQL_DATABASE: "customers"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_USER: "genericuser"